const String = {
    AppName: 'E Grass',
    Name: 'Name',
    Update: 'Update',
    LogIn: 'Log In',
    LogInMessage: 'Please login to use the app',
    SingInMessage: 'Please sign up to enter the app.',
    Email: 'Email',
    RememberMe: 'Remember Me',
    Forgot: 'Forgot Password?',
    Login: 'Login',
    loginAccount: 'Don’t have an account ?',
    SIGNUP: 'Sign Up',
    UserRegistration: 'Sign Up',
    Regi_Email: 'Email',
    agree: 'I agree with Privacy Policy',
    SiginAccount: 'Already have an account ?',
    ForgotPassword: 'Forgot Password',
    ChangePassword: 'Change Password',
    ResetPassword: 'Reset Password',
    Forgotdic: 'Enter email associated with your account',
    Loginup: 'Login',
    EmailAddress: 'Email Address ',
    SendLink: 'Send OTP',
    StepVerification2: '2 Step Verification',
    CodeDigit: 'An otp was just sent to register mobile number ',
    codetext: 'Code',
    Deviceagain: 'Don’t ask on this device again',
    receive: 'Didn’t receive an email?',
    ResendCode: 'Resend Code',
    LinkSent: 'Code Sent!',
    infromations: 'Enter new information below to log in',
    receivelink: 'Didn’t receive the link?',
    ResendLink: 'Resend Link',
    chang_oldPassword: 'Current Password',
    chang_newPassword: 'New Password',
    chang_conPassword: 'Confirm New Password',
    Save: 'Save',
    StepVerification: '2 Step Verification',
    sign_Verfication: 'Please sign up to enter in a app.',
    Continue: 'Continue',
    Confim_NewPassword: 'Confirm New Password',
    FirstName: 'First Name',
    LastName: 'Last Name',
    PhoneNumber: 'Phone Number',
    Password: 'Password',
    ChangePhoto: 'Change Photo',
    ChangePassword: 'Change Password',
    EditProfile: 'Edit Profile',
    Radius: 'Radius',
    mile: '1 mile',
    miles: '200 miles',
    Location: 'Location Name',
    CreatedBy: 'Created By',
    ConfirmBy: 'Confirmed By',
    ConfrimAlert: 'Confirm Alert',
    ReportAlert: 'Report Alert',
    fort: '4.5',
    username: 'John Doe',
    useremail: 'johnd@gmail.com',
    SignOut: 'Sign Out',
    PersonsName: 'Persons Name',
    mago: '5m ago',
    YourReview: 'Your Review',
    YES: 'YES',
    NO: 'NO',
    Submit: 'Submit',
    Cancel: 'Cancel',
    Distance: 'Distance',
    SeeReviews: 'See Reviews',
    CreateAlert: 'Create Alert',
    DeleteAlert: 'Delete Alert',
    Alert: 'Alert Message...',
    AlertMessage: 'Alert Message :',
    Continue: 'Continue',
    AlertMessageHead: 'Alert Message : ',
    AlertMessage: 'dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    PinLocation: 'Set Pin Location',
    Logoutsubmit: "Are you sure you want to Signout?",
    Grn_Details: 'GRN No. : ',
    searchmodal: 'You can also search for specific dishes that you like',
    Search: 'Search',
    Repeat: "Do you want repeat the transaction ?",
    View_Repeat: "Do you want repeat or view the transaction ?",
    UPIfail: "Sorry ! Could not verify the request. Please try again",
    privacy_policy: 'Privacy Policy |',
    TermsCondition: "Terms & Conditions",
    Password_Policy_Head: 'Password must contain',
    term1: "one special character(!@#$), one Uppercase letter(A-Z), one Lowercase letter(a-z), one number(0-9)",
    Filemessage: "E-Challan Successfully Save to Download Folder"
}
export default String;

